export default {
    warehouse: [
        {
            name: 'Склад 1',
            products: [
                {
                    Column1: 0,
                    Product_Name: 'Сливочное масло',
                    Product_Cost: '655.2',
                    Manufacture_Date: 45398.5712037037,
                    Expiry_Date: 45404.5712037037,
                    SKU: 1039,
                    Region: 'Санкт-Петербург',
                    Product_Amount: '600.0',
                    Product_Measure: 'г',
                    Product_Volume: '0.0006',
                    Manufacturer: 'Маслозавод "Сливка"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 1,
                    Product_Name: 'Свинина',
                    Product_Cost: '482.17',
                    Manufacture_Date: 45397.581712962965,
                    Expiry_Date: 45406.581712962965,
                    SKU: 1036,
                    Region: 'Воронеж',
                    Product_Amount: '1.4194',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0017',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 2,
                    Product_Name: 'Сливочное масло',
                    Product_Cost: '190.7',
                    Manufacture_Date: 44459.4834375,
                    Expiry_Date: 44519.4834375,
                    SKU: 1040,
                    Region: 'Воронеж',
                    Product_Amount: '180.0',
                    Product_Measure: 'г',
                    Product_Volume: '0.0002',
                    Manufacturer: 'ОАО "Молокозавод №1"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 3,
                    Product_Name: 'Масло',
                    Product_Cost: '128.7',
                    Manufacture_Date: 44250.5702662037,
                    Expiry_Date: 44280.5702662037,
                    SKU: 1019,
                    Region: 'Санкт-Петербург',
                    Product_Amount: '1.0',
                    Product_Measure: 'л',
                    Product_Volume: '0.001',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 4,
                    Product_Name: 'Молоко',
                    Product_Cost: '79.9',
                    Manufacture_Date: 44608.46853009259,
                    Expiry_Date: 44613.46853009259,
                    SKU: 1003,
                    Region: 'Санкт-Петербург',
                    Product_Amount: '0.93',
                    Product_Measure: 'л',
                    Product_Volume: '0.001',
                    Manufacturer: 'ОАО "Молокозавод №1"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 5,
                    Product_Name: 'Огурцы маринованные',
                    Product_Cost: '91.1',
                    Manufacture_Date: 44632.79662037037,
                    Expiry_Date: 44812.79662037037,
                    SKU: 1037,
                    Region: 'Москва',
                    Product_Amount: '500.0',
                    Product_Measure: 'г',
                    Product_Volume: '0.0007',
                    Manufacturer: 'Овощеводческий кооператив "Зеленый мир"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 6,
                    Product_Name: 'Капуста',
                    Product_Cost: '48.58',
                    Manufacture_Date: 45061.644594907404,
                    Expiry_Date: 45075.644594907404,
                    SKU: 1034,
                    Region: 'Санкт-Петербург',
                    Product_Amount: '1.4247',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0031',
                    Manufacturer: 'Овощеводческий кооператив "Зеленый мир"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 7,
                    Product_Name: 'Сыр',
                    Product_Cost: '2013.1',
                    Manufacture_Date: 44814.55469907408,
                    Expiry_Date: 44874.55469907408,
                    SKU: 1008,
                    Region: 'Санкт-Петербург',
                    Product_Amount: '1.7804',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0019',
                    Manufacturer: 'Фермерское хозяйство "Сырок"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 8,
                    Product_Name: 'Рис',
                    Product_Cost: '167.4',
                    Manufacture_Date: 43934.79846064815,
                    Expiry_Date: 44299.79846064815,
                    SKU: 1027,
                    Region: 'Краснодар',
                    Product_Amount: '3.0',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0036',
                    Manufacturer: 'ООО "Рисовая поляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 9,
                    Product_Name: 'Рис',
                    Product_Cost: '248.0',
                    Manufacture_Date: 44704.68295138889,
                    Expiry_Date: 45069.68295138889,
                    SKU: 1027,
                    Region: 'Тверь',
                    Product_Amount: '4.0',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0048',
                    Manufacturer: 'ООО "Рисовая поляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 10,
                    Product_Name: 'Сливочное масло',
                    Product_Cost: '104.62',
                    Manufacture_Date: 43897.65113425926,
                    Expiry_Date: 43957.65113425926,
                    SKU: 1040,
                    Region: 'Ростов-на-Дону',
                    Product_Amount: '0.5914',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0006',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 11,
                    Product_Name: 'Капуста',
                    Product_Cost: '24.53',
                    Manufacture_Date: 44290.891076388885,
                    Expiry_Date: 44304.891076388885,
                    SKU: 1034,
                    Region: 'Краснодар',
                    Product_Amount: '0.8124',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0018',
                    Manufacturer: 'Овощеводческий кооператив "Зеленый мир"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 12,
                    Product_Name: 'Молоко',
                    Product_Cost: '73.3',
                    Manufacture_Date: 44703.69008101852,
                    Expiry_Date: 44708.69008101852,
                    SKU: 1004,
                    Region: 'Тверь',
                    Product_Amount: '1.4',
                    Product_Measure: 'л',
                    Product_Volume: '0.0015',
                    Manufacturer: 'Фермерское хозяйство "Молочный рай"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 13,
                    Product_Name: 'Сыр',
                    Product_Cost: '793.6',
                    Manufacture_Date: 44363.51395833334,
                    Expiry_Date: 44423.51395833334,
                    SKU: 1044,
                    Region: 'Краснодар',
                    Product_Amount: '1000.0',
                    Product_Measure: 'г',
                    Product_Volume: '0.001',
                    Manufacturer: 'Фермерское хозяйство "Сырок"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 14,
                    Product_Name: 'Сливочное масло',
                    Product_Cost: '218.41',
                    Manufacture_Date: 44050.63695601852,
                    Expiry_Date: 44110.63695601852,
                    SKU: 1040,
                    Region: 'Санкт-Петербург',
                    Product_Amount: '1.1981',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0012',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 15,
                    Product_Name: 'Огурцы',
                    Product_Cost: '91.9',
                    Manufacture_Date: 45007.64538194444,
                    Expiry_Date: 45017.64538194444,
                    SKU: 1010,
                    Region: 'Ростов-на-Дону',
                    Product_Amount: '1.4427',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0023',
                    Manufacturer: 'Овощеводческий кооператив "Зеленый мир"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 16,
                    Product_Name: 'Картофель',
                    Product_Cost: '471.0',
                    Manufacture_Date: 44400.910266203704,
                    Expiry_Date: 44430.910266203704,
                    SKU: 1023,
                    Region: 'Санкт-Петербург',
                    Product_Amount: '25.0',
                    Product_Measure: 'кг',
                    Product_Volume: '0.036',
                    Manufacturer: 'Овощеводческий кооператив "Зеленый мир"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 17,
                    Product_Name: 'Огурцы маринованные',
                    Product_Cost: '95.5',
                    Manufacture_Date: 45223.8559375,
                    Expiry_Date: 45403.8559375,
                    SKU: 1037,
                    Region: 'Воронеж',
                    Product_Amount: '500.0',
                    Product_Measure: 'г',
                    Product_Volume: '0.0007',
                    Manufacturer: 'Овощеводческий кооператив "Зеленый мир"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 18,
                    Product_Name: 'Курица',
                    Product_Cost: '271.44',
                    Manufacture_Date: 44211.61284722222,
                    Expiry_Date: 44216.61284722222,
                    SKU: 1030,
                    Region: 'Санкт-Петербург',
                    Product_Amount: '1.305',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0016',
                    Manufacturer: 'Птицефабрика "Курочка"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 19,
                    Product_Name: 'Сыр',
                    Product_Cost: '1231.81',
                    Manufacture_Date: 43932.504583333335,
                    Expiry_Date: 43992.504583333335,
                    SKU: 1008,
                    Region: 'Краснодар',
                    Product_Amount: '1.2328',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0013',
                    Manufacturer: 'Фермерское хозяйство "Сырок"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 20,
                    Product_Name: 'Хлеб',
                    Product_Cost: '172.5',
                    Manufacture_Date: 45291.50780092592,
                    Expiry_Date: 45298.50780092592,
                    SKU: 1016,
                    Region: 'Краснодар',
                    Product_Amount: '2750.0',
                    Product_Measure: 'г',
                    Product_Volume: '0.0047',
                    Manufacturer: 'ООО "Хлебопекарня "Русский хлеб"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 21,
                    Product_Name: 'Хлеб',
                    Product_Cost: '31.4',
                    Manufacture_Date: 44089.53826388889,
                    Expiry_Date: 44096.53826388889,
                    SKU: 1015,
                    Region: 'Краснодар',
                    Product_Amount: '500.0',
                    Product_Measure: 'г',
                    Product_Volume: '0.0009',
                    Manufacturer: 'Пекарня "Хлебушек"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 22,
                    Product_Name: 'Творог',
                    Product_Cost: '81.7',
                    Manufacture_Date: 44294.602534722224,
                    Expiry_Date: 44314.602534722224,
                    SKU: 1022,
                    Region: 'Воронеж',
                    Product_Amount: '450.0',
                    Product_Measure: 'г',
                    Product_Volume: '0.0005',
                    Manufacturer: 'Фермерское хозяйство "Творожок и молоко"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 23,
                    Product_Name: 'Огурцы маринованные',
                    Product_Cost: '362.0',
                    Manufacture_Date: 44726.699907407405,
                    Expiry_Date: 44906.699907407405,
                    SKU: 1037,
                    Region: 'Санкт-Петербург',
                    Product_Amount: '2000.0',
                    Product_Measure: 'г',
                    Product_Volume: '0.0028',
                    Manufacturer: 'Овощеводческий кооператив "Зеленый мир"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 24,
                    Product_Name: 'Кефир',
                    Product_Cost: '187.2',
                    Manufacture_Date: 44518.71871527778,
                    Expiry_Date: 44525.71871527778,
                    SKU: 1012,
                    Region: 'Воронеж',
                    Product_Amount: '1.8',
                    Product_Measure: 'л',
                    Product_Volume: '0.002',
                    Manufacturer: 'Молочная ферма "Кефирок"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 25,
                    Product_Name: 'Сливочное масло',
                    Product_Cost: '767.6',
                    Manufacture_Date: 44428.718726851854,
                    Expiry_Date: 44488.718726851854,
                    SKU: 1040,
                    Region: 'Москва',
                    Product_Amount: '720.0',
                    Product_Measure: 'г',
                    Product_Volume: '0.0007',
                    Manufacturer: 'ОАО "Молокозавод №1"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 26,
                    Product_Name: 'Свинина',
                    Product_Cost: '405.86',
                    Manufacture_Date: 44250.574282407404,
                    Expiry_Date: 44253.574282407404,
                    SKU: 1035,
                    Region: 'Краснодар',
                    Product_Amount: '1.0878',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0013',
                    Manufacturer: 'Фермерское хозяйство "Свинок"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 27,
                    Product_Name: 'Масло',
                    Product_Cost: '131.7',
                    Manufacture_Date: 44431.91347222222,
                    Expiry_Date: 44461.91347222222,
                    SKU: 1019,
                    Region: 'Ростов-на-Дону',
                    Product_Amount: '1.0',
                    Product_Measure: 'л',
                    Product_Volume: '0.001',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 28,
                    Product_Name: 'Куриное яйцо',
                    Product_Cost: '205.5',
                    Manufacture_Date: 43974.56024305556,
                    Expiry_Date: 43994.56024305556,
                    SKU: 1025,
                    Region: 'Тверь',
                    Product_Amount: '50.0',
                    Product_Measure: 'шт',
                    Product_Volume: '0.008',
                    Manufacturer: 'Птицефабрика "Яичная радость"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 29,
                    Product_Name: 'Капуста',
                    Product_Cost: '42.22',
                    Manufacture_Date: 44874.70025462963,
                    Expiry_Date: 44888.70025462963,
                    SKU: 1034,
                    Region: 'Ростов-на-Дону',
                    Product_Amount: '1.3031',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0029',
                    Manufacturer: 'Овощеводческий кооператив "Зеленый мир"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 30,
                    Product_Name: 'Хлеб',
                    Product_Cost: '32.5',
                    Manufacture_Date: 44988.38422453704,
                    Expiry_Date: 44995.38422453704,
                    SKU: 1016,
                    Region: 'Тверь',
                    Product_Amount: '550.0',
                    Product_Measure: 'г',
                    Product_Volume: '0.0009',
                    Manufacturer: 'ООО "Хлебопекарня "Русский хлеб"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 31,
                    Product_Name: 'Свинина',
                    Product_Cost: '787.91',
                    Manufacture_Date: 44289.645462962966,
                    Expiry_Date: 44292.645462962966,
                    SKU: 1036,
                    Region: 'Ростов-на-Дону',
                    Product_Amount: '2.2422',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0027',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 32,
                    Product_Name: 'Капуста',
                    Product_Cost: '64.09',
                    Manufacture_Date: 45222.380381944444,
                    Expiry_Date: 45236.380381944444,
                    SKU: 1033,
                    Region: 'Ростов-на-Дону',
                    Product_Amount: '1.7607',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0039',
                    Manufacturer: 'Фермерское хозяйство "Капустин"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 33,
                    Product_Name: 'Сливочное масло',
                    Product_Cost: '268.96',
                    Manufacture_Date: 45210.6337037037,
                    Expiry_Date: 45270.6337037037,
                    SKU: 1040,
                    Region: 'Санкт-Петербург',
                    Product_Amount: '1.3012',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0013',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
            ],
        },
        {
            name: 'Склад 2',
            products: [
                {
                    Column1: 34,
                    Product_Name: 'Огурцы',
                    Product_Cost: '21.99',
                    Manufacture_Date: 45394.4834375,
                    Expiry_Date: 45404.4834375,
                    SKU: 1010,
                    Region: 'Москва',
                    Product_Amount: '0.3912',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0006',
                    Manufacturer: 'Овощеводческий кооператив "Зеленый мир"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 35,
                    Product_Name: 'Куриное яйцо',
                    Product_Cost: '145.4',
                    Manufacture_Date: 45392.5702662037,
                    Expiry_Date: 45405.5702662037,
                    SKU: 1026,
                    Region: 'Ростов-на-Дону',
                    Product_Amount: '10.0',
                    Product_Measure: 'шт',
                    Product_Volume: '0.0016',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 36,
                    Product_Name: 'Оливковое масло',
                    Product_Cost: '773.5',
                    Manufacture_Date: 44223.76390046296,
                    Expiry_Date: 44403.76390046296,
                    SKU: 1032,
                    Region: 'Ростов-на-Дону',
                    Product_Amount: '1.0',
                    Product_Measure: 'л',
                    Product_Volume: '0.0011',
                    Manufacturer: 'Фермерское хозяйство "Олива"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 37,
                    Product_Name: 'Морковь',
                    Product_Cost: '95.0',
                    Manufacture_Date: 44716.51215277778,
                    Expiry_Date: 44730.51215277778,
                    SKU: 1014,
                    Region: 'Тверь',
                    Product_Amount: '2.4296',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0034',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 38,
                    Product_Name: 'Морковь',
                    Product_Cost: '59.51',
                    Manufacture_Date: 43858.70746527778,
                    Expiry_Date: 43872.70746527778,
                    SKU: 1013,
                    Region: 'Краснодар',
                    Product_Amount: '1.4804',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0021',
                    Manufacturer: 'Овощеводческий кооператив "Зеленый мир"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 39,
                    Product_Name: 'Морковь',
                    Product_Cost: '78.27',
                    Manufacture_Date: 43847.38071759259,
                    Expiry_Date: 43861.38071759259,
                    SKU: 1014,
                    Region: 'Москва',
                    Product_Amount: '2.2299',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0031',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 40,
                    Product_Name: 'Сыр',
                    Product_Cost: '1101.56',
                    Manufacture_Date: 44175.44200231481,
                    Expiry_Date: 44235.44200231481,
                    SKU: 1043,
                    Region: 'Тверь',
                    Product_Amount: '1.2984',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0014',
                    Manufacturer: 'ОАО "Молокозавод №1"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 41,
                    Product_Name: 'Сливочное масло',
                    Product_Cost: '587.7',
                    Manufacture_Date: 44283.37835648148,
                    Expiry_Date: 44343.37835648148,
                    SKU: 1039,
                    Region: 'Москва',
                    Product_Amount: '600.0',
                    Product_Measure: 'г',
                    Product_Volume: '0.0006',
                    Manufacturer: 'Маслозавод "Сливка"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 42,
                    Product_Name: 'Огурцы',
                    Product_Cost: '74.86',
                    Manufacture_Date: 44184.58555555555,
                    Expiry_Date: 44194.58555555555,
                    SKU: 1009,
                    Region: 'Краснодар',
                    Product_Amount: '1.1715',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0019',
                    Manufacturer: 'Фермерское хозяйство "Огурчик"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 43,
                    Product_Name: 'Рис',
                    Product_Cost: '127.8',
                    Manufacture_Date: 44802.62449074074,
                    Expiry_Date: 45167.62449074074,
                    SKU: 1027,
                    Region: 'Воронеж',
                    Product_Amount: '2.0',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0024',
                    Manufacturer: 'ООО "Рисовая поляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 44,
                    Product_Name: 'Яблоки',
                    Product_Cost: '56.45',
                    Manufacture_Date: 43991.82351851852,
                    Expiry_Date: 43998.82351851852,
                    SKU: 1001,
                    Region: 'Санкт-Петербург',
                    Product_Amount: '1.1047',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0021',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 45,
                    Product_Name: 'Картофель',
                    Product_Cost: '56.19',
                    Manufacture_Date: 45207.73229166667,
                    Expiry_Date: 45237.73229166667,
                    SKU: 1024,
                    Region: 'Краснодар',
                    Product_Amount: '2.0735',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0029',
                    Manufacturer: 'ООО "Картофан"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 46,
                    Product_Name: 'Яблоки',
                    Product_Cost: '61.37',
                    Manufacture_Date: 44640.67234953704,
                    Expiry_Date: 44647.67234953704,
                    SKU: 1001,
                    Region: 'Краснодар',
                    Product_Amount: '1.094',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0021',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 47,
                    Product_Name: 'Курица',
                    Product_Cost: '396.43',
                    Manufacture_Date: 44664.57189814815,
                    Expiry_Date: 44669.57189814815,
                    SKU: 1029,
                    Region: 'Краснодар',
                    Product_Amount: '1.7206',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0021',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 48,
                    Product_Name: 'Огурцы',
                    Product_Cost: '74.92',
                    Manufacture_Date: 44689.82283564815,
                    Expiry_Date: 44697.82283564815,
                    SKU: 1042,
                    Region: 'Краснодар',
                    Product_Amount: '1.3797',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0022',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 49,
                    Product_Name: 'Курица',
                    Product_Cost: '282.95',
                    Manufacture_Date: 45187.39298611111,
                    Expiry_Date: 45192.39298611111,
                    SKU: 1030,
                    Region: 'Москва',
                    Product_Amount: '1.1726',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0014',
                    Manufacturer: 'Птицефабрика "Курочка"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 50,
                    Product_Name: 'Молоко',
                    Product_Cost: '332.4',
                    Manufacture_Date: 45028.8956712963,
                    Expiry_Date: 45033.8956712963,
                    SKU: 1003,
                    Region: 'Воронеж',
                    Product_Amount: '3.72',
                    Product_Measure: 'л',
                    Product_Volume: '0.004',
                    Manufacturer: 'ОАО "Молокозавод №1"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 51,
                    Product_Name: 'Масло',
                    Product_Cost: '241.0',
                    Manufacture_Date: 43861.48121527778,
                    Expiry_Date: 43891.48121527778,
                    SKU: 1019,
                    Region: 'Воронеж',
                    Product_Amount: '2.0',
                    Product_Measure: 'л',
                    Product_Volume: '0.002',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 52,
                    Product_Name: 'Сливочное масло',
                    Product_Cost: '806.0',
                    Manufacture_Date: 44811.757256944446,
                    Expiry_Date: 44871.757256944446,
                    SKU: 1040,
                    Region: 'Ростов-на-Дону',
                    Product_Amount: '720.0',
                    Product_Measure: 'г',
                    Product_Volume: '0.0007',
                    Manufacturer: 'ОАО "Молокозавод №1"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 53,
                    Product_Name: 'Рис',
                    Product_Cost: '337.5',
                    Manufacture_Date: 45000.39304398148,
                    Expiry_Date: 45365.39304398148,
                    SKU: 1027,
                    Region: 'Ростов-на-Дону',
                    Product_Amount: '5.0',
                    Product_Measure: 'кг',
                    Product_Volume: '0.006',
                    Manufacturer: 'ООО "Рисовая поляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 54,
                    Product_Name: 'Яблоки',
                    Product_Cost: '84.07',
                    Manufacture_Date: 44321.41994212963,
                    Expiry_Date: 44328.41994212963,
                    SKU: 1001,
                    Region: 'Ростов-на-Дону',
                    Product_Amount: '1.5511',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0029',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 55,
                    Product_Name: 'Сливочное масло',
                    Product_Cost: '540.0',
                    Manufacture_Date: 44007.456875,
                    Expiry_Date: 44067.456875,
                    SKU: 1040,
                    Region: 'Воронеж',
                    Product_Amount: '540.0',
                    Product_Measure: 'г',
                    Product_Volume: '0.0005',
                    Manufacturer: 'ОАО "Молокозавод №1"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 56,
                    Product_Name: 'Капуста',
                    Product_Cost: '30.88',
                    Manufacture_Date: 44198.419444444444,
                    Expiry_Date: 44212.419444444444,
                    SKU: 1034,
                    Region: 'Краснодар',
                    Product_Amount: '1.0467',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0023',
                    Manufacturer: 'Овощеводческий кооператив "Зеленый мир"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 57,
                    Product_Name: 'Капуста',
                    Product_Cost: '57.12',
                    Manufacture_Date: 45104.53380787037,
                    Expiry_Date: 45118.53380787037,
                    SKU: 1033,
                    Region: 'Санкт-Петербург',
                    Product_Amount: '1.5273',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0034',
                    Manufacturer: 'Фермерское хозяйство "Капустин"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 58,
                    Product_Name: 'Картофель',
                    Product_Cost: '37.31',
                    Manufacture_Date: 44656.66983796296,
                    Expiry_Date: 44686.66983796296,
                    SKU: 1024,
                    Region: 'Краснодар',
                    Product_Amount: '1.4573',
                    Product_Measure: 'кг',
                    Product_Volume: '0.002',
                    Manufacturer: 'ООО "Картофан"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 59,
                    Product_Name: 'Хлеб',
                    Product_Cost: '133.6',
                    Manufacture_Date: 44844.8559375,
                    Expiry_Date: 44851.8559375,
                    SKU: 1016,
                    Region: 'Краснодар',
                    Product_Amount: '2200.0',
                    Product_Measure: 'г',
                    Product_Volume: '0.0038',
                    Manufacturer: 'ООО "Хлебопекарня "Русский хлеб"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 60,
                    Product_Name: 'Сыр',
                    Product_Cost: '680.4',
                    Manufacture_Date: 45254.67790509259,
                    Expiry_Date: 45314.67790509259,
                    SKU: 1044,
                    Region: 'Ростов-на-Дону',
                    Product_Amount: '750.0',
                    Product_Measure: 'г',
                    Product_Volume: '0.0008',
                    Manufacturer: 'Фермерское хозяйство "Сырок"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 61,
                    Product_Name: 'Свекла',
                    Product_Cost: '54.07',
                    Manufacture_Date: 44177.420335648145,
                    Expiry_Date: 44187.420335648145,
                    SKU: 1018,
                    Region: 'Воронеж',
                    Product_Amount: '1.5448',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0023',
                    Manufacturer: 'Овощеводческий кооператив "Зеленый мир"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 62,
                    Product_Name: 'Огурцы',
                    Product_Cost: '83.13',
                    Manufacture_Date: 45216.46053240741,
                    Expiry_Date: 45226.46053240741,
                    SKU: 1010,
                    Region: 'Ростов-на-Дону',
                    Product_Amount: '1.277',
                    Product_Measure: 'кг',
                    Product_Volume: '0.002',
                    Manufacturer: 'Овощеводческий кооператив "Зеленый мир"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 63,
                    Product_Name: 'Кефир',
                    Product_Cost: '212.6',
                    Manufacture_Date: 44934.52732638889,
                    Expiry_Date: 44941.52732638889,
                    SKU: 1011,
                    Region: 'Санкт-Петербург',
                    Product_Amount: '2.0',
                    Product_Measure: 'л',
                    Product_Volume: '0.0022',
                    Manufacturer: 'ОАО "Молокозавод №1"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 64,
                    Product_Name: 'Картофель',
                    Product_Cost: '34.16',
                    Manufacture_Date: 45052.641493055555,
                    Expiry_Date: 45082.641493055555,
                    SKU: 1024,
                    Region: 'Санкт-Петербург',
                    Product_Amount: '1.2557',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0018',
                    Manufacturer: 'ООО "Картофан"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
            ],
        },
        {
            name: 'Склад 3',
            products: [
                {
                    Column1: 65,
                    Product_Name: 'Огурцы',
                    Product_Cost: '85.45',
                    Manufacture_Date: 45395.46853009259,
                    Expiry_Date: 45407.46853009259,
                    SKU: 1042,
                    Region: 'Санкт-Петербург',
                    Product_Amount: '1.7367',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0028',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 66,
                    Product_Name: 'Капуста',
                    Product_Cost: '62.73',
                    Manufacture_Date: 44381.51605324074,
                    Expiry_Date: 44395.51605324074,
                    SKU: 1034,
                    Region: 'Краснодар',
                    Product_Amount: '2.0433',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0045',
                    Manufacturer: 'Овощеводческий кооператив "Зеленый мир"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 67,
                    Product_Name: 'Сливочное масло',
                    Product_Cost: '405.4',
                    Manufacture_Date: 44594.732256944444,
                    Expiry_Date: 44654.732256944444,
                    SKU: 1039,
                    Region: 'Краснодар',
                    Product_Amount: '400.0',
                    Product_Measure: 'г',
                    Product_Volume: '0.0004',
                    Manufacturer: 'Маслозавод "Сливка"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 68,
                    Product_Name: 'Кефир',
                    Product_Cost: '371.6',
                    Manufacture_Date: 44436.907685185186,
                    Expiry_Date: 44443.907685185186,
                    SKU: 1012,
                    Region: 'Воронеж',
                    Product_Amount: '3.6',
                    Product_Measure: 'л',
                    Product_Volume: '0.004',
                    Manufacturer: 'Молочная ферма "Кефирок"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 69,
                    Product_Name: 'Огурцы',
                    Product_Cost: '97.16',
                    Manufacture_Date: 45137.81685185185,
                    Expiry_Date: 45147.81685185185,
                    SKU: 1010,
                    Region: 'Ростов-на-Дону',
                    Product_Amount: '1.5041',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0024',
                    Manufacturer: 'Овощеводческий кооператив "Зеленый мир"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 70,
                    Product_Name: 'Рис',
                    Product_Cost: '278.0',
                    Manufacture_Date: 44456.49747685185,
                    Expiry_Date: 44821.49747685185,
                    SKU: 1028,
                    Region: 'Санкт-Петербург',
                    Product_Amount: '4.5',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0055',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 71,
                    Product_Name: 'Кефир',
                    Product_Cost: '292.2',
                    Manufacture_Date: 44635.61850694445,
                    Expiry_Date: 44642.61850694445,
                    SKU: 1012,
                    Region: 'Санкт-Петербург',
                    Product_Amount: '2.7',
                    Product_Measure: 'л',
                    Product_Volume: '0.003',
                    Manufacturer: 'Молочная ферма "Кефирок"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 72,
                    Product_Name: 'Рис',
                    Product_Cost: '111.6',
                    Manufacture_Date: 44433.52013888889,
                    Expiry_Date: 44798.52013888889,
                    SKU: 1028,
                    Region: 'Краснодар',
                    Product_Amount: '1.8',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0022',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 73,
                    Product_Name: 'Свинина',
                    Product_Cost: '802.25',
                    Manufacture_Date: 44848.43004629629,
                    Expiry_Date: 44851.43004629629,
                    SKU: 1035,
                    Region: 'Тверь',
                    Product_Amount: '1.9308',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0023',
                    Manufacturer: 'Фермерское хозяйство "Свинок"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 74,
                    Product_Name: 'Картофель',
                    Product_Cost: '39.07',
                    Manufacture_Date: 44363.82046296296,
                    Expiry_Date: 44393.82046296296,
                    SKU: 1024,
                    Region: 'Ростов-на-Дону',
                    Product_Amount: '1.6485',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0023',
                    Manufacturer: 'ООО "Картофан"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 75,
                    Product_Name: 'Сливочное масло',
                    Product_Cost: '205.21',
                    Manufacture_Date: 44801.765601851854,
                    Expiry_Date: 44861.765601851854,
                    SKU: 1040,
                    Region: 'Москва',
                    Product_Amount: '1.0245',
                    Product_Measure: 'кг',
                    Product_Volume: '0.001',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 76,
                    Product_Name: 'Яблоки',
                    Product_Cost: '94.37',
                    Manufacture_Date: 44660.46092592592,
                    Expiry_Date: 44667.46092592592,
                    SKU: 1001,
                    Region: 'Санкт-Петербург',
                    Product_Amount: '1.6851',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0032',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 77,
                    Product_Name: 'Хлеб',
                    Product_Cost: '37.7',
                    Manufacture_Date: 45221.509664351855,
                    Expiry_Date: 45228.509664351855,
                    SKU: 1015,
                    Region: 'Санкт-Петербург',
                    Product_Amount: '500.0',
                    Product_Measure: 'г',
                    Product_Volume: '0.0009',
                    Manufacturer: 'Пекарня "Хлебушек"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 78,
                    Product_Name: 'Рис',
                    Product_Cost: '57.9',
                    Manufacture_Date: 44980.49172453704,
                    Expiry_Date: 45345.49172453704,
                    SKU: 1028,
                    Region: 'Ростов-на-Дону',
                    Product_Amount: '0.9',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0011',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 79,
                    Product_Name: 'Капуста',
                    Product_Cost: '54.52',
                    Manufacture_Date: 44216.71947916667,
                    Expiry_Date: 44230.71947916667,
                    SKU: 1033,
                    Region: 'Краснодар',
                    Product_Amount: '1.6984',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0037',
                    Manufacturer: 'Фермерское хозяйство "Капустин"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 80,
                    Product_Name: 'Сыр',
                    Product_Cost: '1126.4',
                    Manufacture_Date: 44983.708333333336,
                    Expiry_Date: 45023.708333333336,
                    SKU: 1041,
                    Region: 'Москва',
                    Product_Amount: '1000.0',
                    Product_Measure: 'г',
                    Product_Volume: '0.001',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 81,
                    Product_Name: 'Сыр',
                    Product_Cost: '181.6',
                    Manufacture_Date: 43882.91055555556,
                    Expiry_Date: 43942.91055555556,
                    SKU: 1044,
                    Region: 'Тверь',
                    Product_Amount: '250.0',
                    Product_Measure: 'г',
                    Product_Volume: '0.0003',
                    Manufacturer: 'Фермерское хозяйство "Сырок"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 82,
                    Product_Name: 'Сыр',
                    Product_Cost: '2665.04',
                    Manufacture_Date: 44176.569710648146,
                    Expiry_Date: 44236.569710648146,
                    SKU: 1008,
                    Region: 'Краснодар',
                    Product_Amount: '2.5975',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0027',
                    Manufacturer: 'Фермерское хозяйство "Сырок"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 83,
                    Product_Name: 'Яблоки',
                    Product_Cost: '85.23',
                    Manufacture_Date: 44819.54025462963,
                    Expiry_Date: 44826.54025462963,
                    SKU: 1002,
                    Region: 'Ростов-на-Дону',
                    Product_Amount: '1.668',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0033',
                    Manufacturer: 'Фермерское хозяйство "Яблочкин"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 84,
                    Product_Name: 'Творог',
                    Product_Cost: '189.0',
                    Manufacture_Date: 44996.445972222224,
                    Expiry_Date: 45016.445972222224,
                    SKU: 1021,
                    Region: 'Москва',
                    Product_Amount: '800.0',
                    Product_Measure: 'г',
                    Product_Volume: '0.0009',
                    Manufacturer: 'ОАО "Молокозавод №1"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 85,
                    Product_Name: 'Сыр',
                    Product_Cost: '199.9',
                    Manufacture_Date: 44468.58936342593,
                    Expiry_Date: 44528.58936342593,
                    SKU: 1044,
                    Region: 'Ростов-на-Дону',
                    Product_Amount: '250.0',
                    Product_Measure: 'г',
                    Product_Volume: '0.0003',
                    Manufacturer: 'Фермерское хозяйство "Сырок"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 86,
                    Product_Name: 'Яблоки',
                    Product_Cost: '55.31',
                    Manufacture_Date: 44410.74423611111,
                    Expiry_Date: 44417.74423611111,
                    SKU: 1002,
                    Region: 'Ростов-на-Дону',
                    Product_Amount: '1.1242',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0022',
                    Manufacturer: 'Фермерское хозяйство "Яблочкин"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 87,
                    Product_Name: 'Куриное яйцо',
                    Product_Cost: '89.6',
                    Manufacture_Date: 44555.64685185185,
                    Expiry_Date: 44575.64685185185,
                    SKU: 1025,
                    Region: 'Санкт-Петербург',
                    Product_Amount: '20.0',
                    Product_Measure: 'шт',
                    Product_Volume: '0.0032',
                    Manufacturer: 'Птицефабрика "Яичная радость"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 88,
                    Product_Name: 'Свекла',
                    Product_Cost: '53.75',
                    Manufacture_Date: 44388.88706018519,
                    Expiry_Date: 44398.88706018519,
                    SKU: 1017,
                    Region: 'Москва',
                    Product_Amount: '1.4256',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0021',
                    Manufacturer: 'ООО "Ферма Свекольная"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 89,
                    Product_Name: 'Масло',
                    Product_Cost: '252.0',
                    Manufacture_Date: 44129.65626157408,
                    Expiry_Date: 44159.65626157408,
                    SKU: 1019,
                    Region: 'Краснодар',
                    Product_Amount: '2.0',
                    Product_Measure: 'л',
                    Product_Volume: '0.002',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 90,
                    Product_Name: 'Хлеб',
                    Product_Cost: '161.5',
                    Manufacture_Date: 44354.46810185185,
                    Expiry_Date: 44361.46810185185,
                    SKU: 1015,
                    Region: 'Краснодар',
                    Product_Amount: '2500.0',
                    Product_Measure: 'г',
                    Product_Volume: '0.0045',
                    Manufacturer: 'Пекарня "Хлебушек"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 91,
                    Product_Name: 'Мед',
                    Product_Cost: '1503.0',
                    Manufacture_Date: 44253.77305555555,
                    Expiry_Date: 44343.77305555555,
                    SKU: 1006,
                    Region: 'Краснодар',
                    Product_Amount: '2000.0',
                    Product_Measure: 'г',
                    Product_Volume: '0.0015',
                    Manufacturer: 'Пасека "Медовый рай"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 92,
                    Product_Name: 'Рис',
                    Product_Cost: '134.4',
                    Manufacture_Date: 45194.736122685186,
                    Expiry_Date: 45559.736122685186,
                    SKU: 1027,
                    Region: 'Ростов-на-Дону',
                    Product_Amount: '2.0',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0024',
                    Manufacturer: 'ООО "Рисовая поляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 93,
                    Product_Name: 'Оливковое масло',
                    Product_Cost: '333.8',
                    Manufacture_Date: 44941.669074074074,
                    Expiry_Date: 45121.669074074074,
                    SKU: 1032,
                    Region: 'Тверь',
                    Product_Amount: '0.4',
                    Product_Measure: 'л',
                    Product_Volume: '0.0004',
                    Manufacturer: 'Фермерское хозяйство "Олива"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 94,
                    Product_Name: 'Рис',
                    Product_Cost: '119.8',
                    Manufacture_Date: 44331.523506944446,
                    Expiry_Date: 44696.523506944446,
                    SKU: 1027,
                    Region: 'Воронеж',
                    Product_Amount: '2.0',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0024',
                    Manufacturer: 'ООО "Рисовая поляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 95,
                    Product_Name: 'Огурцы',
                    Product_Cost: '121.64',
                    Manufacture_Date: 44348.962847222225,
                    Expiry_Date: 44358.54618055555,
                    SKU: 1009,
                    Region: 'Тверь',
                    Product_Amount: '1.8859',
                    Product_Measure: 'кг',
                    Product_Volume: '0.003',
                    Manufacturer: 'Фермерское хозяйство "Огурчик"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
            ],
        },
    ],
    shop: [
        {
            name: 'Магазин 1',
            products: [
                {
                    Column1: 0,
                    Product_Name: 'Сливочное масло',
                    Product_Cost: '655.2',
                    Manufacture_Date: 45398.5712037037,
                    Expiry_Date: 45404.5712037037,
                    SKU: 1039,
                    Region: 'Санкт-Петербург',
                    Product_Amount: '600.0',
                    Product_Measure: 'г',
                    Product_Volume: '0.0006',
                    Manufacturer: 'Маслозавод "Сливка"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 1,
                    Product_Name: 'Свинина',
                    Product_Cost: '482.17',
                    Manufacture_Date: 45397.581712962965,
                    Expiry_Date: 45406.581712962965,
                    SKU: 1036,
                    Region: 'Воронеж',
                    Product_Amount: '1.4194',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0017',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 2,
                    Product_Name: 'Сливочное масло',
                    Product_Cost: '190.7',
                    Manufacture_Date: 44459.4834375,
                    Expiry_Date: 44519.4834375,
                    SKU: 1040,
                    Region: 'Воронеж',
                    Product_Amount: '180.0',
                    Product_Measure: 'г',
                    Product_Volume: '0.0002',
                    Manufacturer: 'ОАО "Молокозавод №1"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 3,
                    Product_Name: 'Масло',
                    Product_Cost: '128.7',
                    Manufacture_Date: 44250.5702662037,
                    Expiry_Date: 44280.5702662037,
                    SKU: 1019,
                    Region: 'Санкт-Петербург',
                    Product_Amount: '1.0',
                    Product_Measure: 'л',
                    Product_Volume: '0.001',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 4,
                    Product_Name: 'Молоко',
                    Product_Cost: '79.9',
                    Manufacture_Date: 44608.46853009259,
                    Expiry_Date: 44613.46853009259,
                    SKU: 1003,
                    Region: 'Санкт-Петербург',
                    Product_Amount: '0.93',
                    Product_Measure: 'л',
                    Product_Volume: '0.001',
                    Manufacturer: 'ОАО "Молокозавод №1"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 5,
                    Product_Name: 'Огурцы маринованные',
                    Product_Cost: '91.1',
                    Manufacture_Date: 44632.79662037037,
                    Expiry_Date: 44812.79662037037,
                    SKU: 1037,
                    Region: 'Москва',
                    Product_Amount: '500.0',
                    Product_Measure: 'г',
                    Product_Volume: '0.0007',
                    Manufacturer: 'Овощеводческий кооператив "Зеленый мир"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 6,
                    Product_Name: 'Капуста',
                    Product_Cost: '48.58',
                    Manufacture_Date: 45061.644594907404,
                    Expiry_Date: 45075.644594907404,
                    SKU: 1034,
                    Region: 'Санкт-Петербург',
                    Product_Amount: '1.4247',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0031',
                    Manufacturer: 'Овощеводческий кооператив "Зеленый мир"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 7,
                    Product_Name: 'Сыр',
                    Product_Cost: '2013.1',
                    Manufacture_Date: 44814.55469907408,
                    Expiry_Date: 44874.55469907408,
                    SKU: 1008,
                    Region: 'Санкт-Петербург',
                    Product_Amount: '1.7804',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0019',
                    Manufacturer: 'Фермерское хозяйство "Сырок"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 8,
                    Product_Name: 'Рис',
                    Product_Cost: '167.4',
                    Manufacture_Date: 43934.79846064815,
                    Expiry_Date: 44299.79846064815,
                    SKU: 1027,
                    Region: 'Краснодар',
                    Product_Amount: '3.0',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0036',
                    Manufacturer: 'ООО "Рисовая поляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 9,
                    Product_Name: 'Рис',
                    Product_Cost: '248.0',
                    Manufacture_Date: 44704.68295138889,
                    Expiry_Date: 45069.68295138889,
                    SKU: 1027,
                    Region: 'Тверь',
                    Product_Amount: '4.0',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0048',
                    Manufacturer: 'ООО "Рисовая поляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 10,
                    Product_Name: 'Сливочное масло',
                    Product_Cost: '104.62',
                    Manufacture_Date: 43897.65113425926,
                    Expiry_Date: 43957.65113425926,
                    SKU: 1040,
                    Region: 'Ростов-на-Дону',
                    Product_Amount: '0.5914',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0006',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
            ],
        },
        {
            name: 'Магазин 2',
            products: [
                {
                    Column1: 34,
                    Product_Name: 'Огурцы',
                    Product_Cost: '21.99',
                    Manufacture_Date: 45394.4834375,
                    Expiry_Date: 45404.4834375,
                    SKU: 1010,
                    Region: 'Москва',
                    Product_Amount: '0.3912',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0006',
                    Manufacturer: 'Овощеводческий кооператив "Зеленый мир"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 35,
                    Product_Name: 'Куриное яйцо',
                    Product_Cost: '145.4',
                    Manufacture_Date: 45392.5702662037,
                    Expiry_Date: 45405.5702662037,
                    SKU: 1026,
                    Region: 'Ростов-на-Дону',
                    Product_Amount: '10.0',
                    Product_Measure: 'шт',
                    Product_Volume: '0.0016',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 41,
                    Product_Name: 'Сливочное масло',
                    Product_Cost: '587.7',
                    Manufacture_Date: 44283.37835648148,
                    Expiry_Date: 44343.37835648148,
                    SKU: 1039,
                    Region: 'Москва',
                    Product_Amount: '600.0',
                    Product_Measure: 'г',
                    Product_Volume: '0.0006',
                    Manufacturer: 'Маслозавод "Сливка"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 42,
                    Product_Name: 'Огурцы',
                    Product_Cost: '74.86',
                    Manufacture_Date: 44184.58555555555,
                    Expiry_Date: 44194.58555555555,
                    SKU: 1009,
                    Region: 'Краснодар',
                    Product_Amount: '1.1715',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0019',
                    Manufacturer: 'Фермерское хозяйство "Огурчик"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 43,
                    Product_Name: 'Рис',
                    Product_Cost: '127.8',
                    Manufacture_Date: 44802.62449074074,
                    Expiry_Date: 45167.62449074074,
                    SKU: 1027,
                    Region: 'Воронеж',
                    Product_Amount: '2.0',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0024',
                    Manufacturer: 'ООО "Рисовая поляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 44,
                    Product_Name: 'Яблоки',
                    Product_Cost: '56.45',
                    Manufacture_Date: 43991.82351851852,
                    Expiry_Date: 43998.82351851852,
                    SKU: 1001,
                    Region: 'Санкт-Петербург',
                    Product_Amount: '1.1047',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0021',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 45,
                    Product_Name: 'Картофель',
                    Product_Cost: '56.19',
                    Manufacture_Date: 45207.73229166667,
                    Expiry_Date: 45237.73229166667,
                    SKU: 1024,
                    Region: 'Краснодар',
                    Product_Amount: '2.0735',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0029',
                    Manufacturer: 'ООО "Картофан"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 46,
                    Product_Name: 'Яблоки',
                    Product_Cost: '61.37',
                    Manufacture_Date: 44640.67234953704,
                    Expiry_Date: 44647.67234953704,
                    SKU: 1001,
                    Region: 'Краснодар',
                    Product_Amount: '1.094',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0021',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 47,
                    Product_Name: 'Курица',
                    Product_Cost: '396.43',
                    Manufacture_Date: 44664.57189814815,
                    Expiry_Date: 44669.57189814815,
                    SKU: 1029,
                    Region: 'Краснодар',
                    Product_Amount: '1.7206',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0021',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 48,
                    Product_Name: 'Огурцы',
                    Product_Cost: '74.92',
                    Manufacture_Date: 44689.82283564815,
                    Expiry_Date: 44697.82283564815,
                    SKU: 1042,
                    Region: 'Краснодар',
                    Product_Amount: '1.3797',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0022',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 49,
                    Product_Name: 'Курица',
                    Product_Cost: '282.95',
                    Manufacture_Date: 45187.39298611111,
                    Expiry_Date: 45192.39298611111,
                    SKU: 1030,
                    Region: 'Москва',
                    Product_Amount: '1.1726',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0014',
                    Manufacturer: 'Птицефабрика "Курочка"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 50,
                    Product_Name: 'Молоко',
                    Product_Cost: '332.4',
                    Manufacture_Date: 45028.8956712963,
                    Expiry_Date: 45033.8956712963,
                    SKU: 1003,
                    Region: 'Воронеж',
                    Product_Amount: '3.72',
                    Product_Measure: 'л',
                    Product_Volume: '0.004',
                    Manufacturer: 'ОАО "Молокозавод №1"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 51,
                    Product_Name: 'Масло',
                    Product_Cost: '241.0',
                    Manufacture_Date: 43861.48121527778,
                    Expiry_Date: 43891.48121527778,
                    SKU: 1019,
                    Region: 'Воронеж',
                    Product_Amount: '2.0',
                    Product_Measure: 'л',
                    Product_Volume: '0.002',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 52,
                    Product_Name: 'Сливочное масло',
                    Product_Cost: '806.0',
                    Manufacture_Date: 44811.757256944446,
                    Expiry_Date: 44871.757256944446,
                    SKU: 1040,
                    Region: 'Ростов-на-Дону',
                    Product_Amount: '720.0',
                    Product_Measure: 'г',
                    Product_Volume: '0.0007',
                    Manufacturer: 'ОАО "Молокозавод №1"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
            ],
        },
        {
            name: 'Магазин 3',
            products: [
                {
                    Column1: 65,
                    Product_Name: 'Огурцы',
                    Product_Cost: '85.45',
                    Manufacture_Date: 45395.46853009259,
                    Expiry_Date: 45407.46853009259,
                    SKU: 1042,
                    Region: 'Санкт-Петербург',
                    Product_Amount: '1.7367',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0028',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 70,
                    Product_Name: 'Рис',
                    Product_Cost: '278.0',
                    Manufacture_Date: 44456.49747685185,
                    Expiry_Date: 44821.49747685185,
                    SKU: 1028,
                    Region: 'Санкт-Петербург',
                    Product_Amount: '4.5',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0055',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 71,
                    Product_Name: 'Кефир',
                    Product_Cost: '292.2',
                    Manufacture_Date: 44635.61850694445,
                    Expiry_Date: 44642.61850694445,
                    SKU: 1012,
                    Region: 'Санкт-Петербург',
                    Product_Amount: '2.7',
                    Product_Measure: 'л',
                    Product_Volume: '0.003',
                    Manufacturer: 'Молочная ферма "Кефирок"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 72,
                    Product_Name: 'Рис',
                    Product_Cost: '111.6',
                    Manufacture_Date: 44433.52013888889,
                    Expiry_Date: 44798.52013888889,
                    SKU: 1028,
                    Region: 'Краснодар',
                    Product_Amount: '1.8',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0022',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 73,
                    Product_Name: 'Свинина',
                    Product_Cost: '802.25',
                    Manufacture_Date: 44848.43004629629,
                    Expiry_Date: 44851.43004629629,
                    SKU: 1035,
                    Region: 'Тверь',
                    Product_Amount: '1.9308',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0023',
                    Manufacturer: 'Фермерское хозяйство "Свинок"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 74,
                    Product_Name: 'Картофель',
                    Product_Cost: '39.07',
                    Manufacture_Date: 44363.82046296296,
                    Expiry_Date: 44393.82046296296,
                    SKU: 1024,
                    Region: 'Ростов-на-Дону',
                    Product_Amount: '1.6485',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0023',
                    Manufacturer: 'ООО "Картофан"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 75,
                    Product_Name: 'Сливочное масло',
                    Product_Cost: '205.21',
                    Manufacture_Date: 44801.765601851854,
                    Expiry_Date: 44861.765601851854,
                    SKU: 1040,
                    Region: 'Москва',
                    Product_Amount: '1.0245',
                    Product_Measure: 'кг',
                    Product_Volume: '0.001',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 76,
                    Product_Name: 'Яблоки',
                    Product_Cost: '94.37',
                    Manufacture_Date: 44660.46092592592,
                    Expiry_Date: 44667.46092592592,
                    SKU: 1001,
                    Region: 'Санкт-Петербург',
                    Product_Amount: '1.6851',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0032',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 77,
                    Product_Name: 'Хлеб',
                    Product_Cost: '37.7',
                    Manufacture_Date: 45221.509664351855,
                    Expiry_Date: 45228.509664351855,
                    SKU: 1015,
                    Region: 'Санкт-Петербург',
                    Product_Amount: '500.0',
                    Product_Measure: 'г',
                    Product_Volume: '0.0009',
                    Manufacturer: 'Пекарня "Хлебушек"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 78,
                    Product_Name: 'Рис',
                    Product_Cost: '57.9',
                    Manufacture_Date: 44980.49172453704,
                    Expiry_Date: 45345.49172453704,
                    SKU: 1028,
                    Region: 'Ростов-на-Дону',
                    Product_Amount: '0.9',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0011',
                    Manufacturer: 'Агроконцерн "ЭкоПоляна"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
                {
                    Column1: 79,
                    Product_Name: 'Капуста',
                    Product_Cost: '54.52',
                    Manufacture_Date: 44216.71947916667,
                    Expiry_Date: 44230.71947916667,
                    SKU: 1033,
                    Region: 'Краснодар',
                    Product_Amount: '1.6984',
                    Product_Measure: 'кг',
                    Product_Volume: '0.0037',
                    Manufacturer: 'Фермерское хозяйство "Капустин"',
                    Product_Quantity: 100,
                    Name_Warehouse: 'Склад 1',
                },
            ],
        },
    ],
};
